### ISSUE TITLE
Laser does not track correctly.

### ISSUE THREAD

**Issue by alec-hs** [deltagamer/DEGA_Wildcats#3]
The laser for the copilot does not track to the position of the camera  - it stays locked to the point that it was turned on at.

**Comment by OpforStretch** [comment]
Hey Alec,

Cheers for letting me know, I only just noticed your opened issues unfortunately. I'll try and get a hotfix for all of these issues you have mentioned hopefully by this weekend.

Thanks,
Delta.

**Comment by OpforStretch** [comment]
Issue now fixed, thanks again.
