### ISSUE TITLE
Suggestion: Co-pilot lock camera

### ISSUE THREAD

**Issue by alexcroox** [deltagamer/DEGA_Wildcats#4]
Would be great to give the co-pilot the ability to lock the current camera view center like you can with the UAV (CTRL + T). Especially useful when lasing a target.

**Comment by OpforStretch** [comment]
Hey Alex,

I believe this is only a feature for UAVs. I think with how kimi set it up you should be able to zoom into a certain level and the camera will auto lock by default, similar to the vanilla UAVs.

Hope it helps,
Delta.
